"""
ADK Integration Layer for Weight Loss Chat Agent.

This module provides the integration layer between the Telegram bot and
Google ADK agents. It uses the ADK Runner framework to properly execute
agents and handle their responses.

Key features:
- ADK Runner integration for agent execution
- Async message processing with proper event handling
- Session management for conversation continuity
- Error handling and logging
- Response formatting for Telegram
"""

import asyncio
import logging
from typing import Dict, Any, Optional, AsyncGenerator
from datetime import datetime

from google.adk.runners import InMemoryRunner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from agents.root.agent import root_agent
from agents.nutrition.agent import nutrition_agent
from config.logging import get_logger

logger = get_logger(__name__)


class ADKAgentRunner:
    """
    ADK Agent Runner for executing agents with proper session management.

    This class manages the ADK Runner lifecycle and provides methods to
    execute agents asynchronously with proper event handling.
    """

    def __init__(self):
        """Initialize the ADK agent runner."""
        self.runner = None
        self.session_service = InMemorySessionService()
        self._initialized = False

    async def initialize(self):
        """Initialize the ADK runner with agents."""
        if self._initialized:
            return

        logger.info("Initializing ADK Runner...")

        try:
            # Create runner with root agent
            self.runner = InMemoryRunner(
                agent=root_agent,
                app_name="agents"  # Match the agent's directory
            )

            # Initialize the runner context
            async with self.runner:
                logger.info("ADK Runner initialized successfully")
                self._initialized = True

        except Exception as e:
            logger.error(f"Failed to initialize ADK Runner: {e}")
            raise

    async def process_message(
        self,
        user_id: str,
        message: str,
        session_id: Optional[str] = None,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Process a message using the ADK agent framework.

        Args:
            user_id: User identifier
            message: User message text
            session_id: Optional session ID (generated if not provided)
            context: Optional context data

        Returns:
            Dict with 'text' and optional 'keyboard' fields
        """
        if not self._initialized:
            await self.initialize()

        # Generate session ID if not provided
        if not session_id:
            session_id = f"session_{user_id}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}"

        logger.info(f"Processing message for user {user_id}, session {session_id}: {message[:100]}...")

        try:
            logger.info(f"📤 Sending message to ADK agent: {message}")

            # Use run_debug for simpler testing (handles session management automatically)
            events = await self.runner.run_debug(
                user_messages=[message],
                user_id=user_id,
                session_id=session_id,
                verbose=True
            )

            logger.info(f"� Total events received: {len(events)}")

            logger.info(f"📊 Total events received: {len(events)}")

            # Process events to extract response
            response_text = ""
            keyboard = None

            for event in events:
                logger.debug(f"🔍 Processing event: {event}")

                if hasattr(event, 'content') and event.content:
                    # Extract text from content
                    for part in event.content.parts:
                        if hasattr(part, 'text'):
                            response_text += part.text
                            logger.info(f"💬 Extracted text from event: {part.text[:100]}...")

                # Handle tool calls and other events
                if hasattr(event, 'tool_call') and event.tool_call:
                    logger.info(f"🔧 Tool call detected: {event.tool_call}")

                # Handle function calls (for nutrition agent)
                if hasattr(event, 'function_call') and event.function_call:
                    logger.info(f"⚙️ Function call detected: {event.function_call}")

            # If no response text, provide fallback
            if not response_text.strip():
                logger.warning("⚠️ No response text generated by agent, using fallback")
                response_text = "I processed your message but don't have a specific response. How can I help you with your weight loss journey?"

            logger.info(f"✅ Agent response generated: {response_text[:200]}...")

            return {
                'text': response_text,
                'keyboard': keyboard,
                'session_id': session_id
            }

        except Exception as e:
            logger.error(f"Error processing message with ADK agent: {e}", exc_info=True)
            return {
                'text': "❌ Sorry, I encountered an error processing your message. Please try again.",
                'session_id': session_id
            }

    async def get_session_history(self, user_id: str, session_id: str) -> Optional[Dict[str, Any]]:
        """
        Get session history for debugging.

        Args:
            user_id: User identifier
            session_id: Session identifier

        Returns:
            Session data if found
        """
        try:
            # This would require access to session data
            # For now, return None as InMemorySessionService doesn't expose this easily
            return None
        except Exception as e:
            logger.error(f"Error getting session history: {e}")
            return None

    async def close(self):
        """Close the runner and cleanup resources."""
        if self.runner:
            await self.runner.close()
            self._initialized = False
            logger.info("ADK Runner closed")


# Global runner instance
agent_runner = ADKAgentRunner()


async def process_agent_message(
    user_id: str,
    message: str,
    session_id: Optional[str] = None,
    context: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Process a message using the ADK agent framework.

    This is the main entry point for the Telegram bot integration.

    Args:
        user_id: User identifier
        message: User message text
        session_id: Optional session ID
        context: Optional context data

    Returns:
        Dict with response data
    """
    try:
        return await agent_runner.process_message(user_id, message, session_id, context)
    except Exception as e:
        logger.error(f"Error in process_agent_message: {e}", exc_info=True)
        return {
            'text': "❌ Sorry, I encountered an error. Please try again."
        }


async def initialize_agent_runner():
    """Initialize the global agent runner."""
    await agent_runner.initialize()


async def shutdown_agent_runner():
    """Shutdown the global agent runner."""
    await agent_runner.close()


# Export functions for easy import
__all__ = [
    'ADKAgentRunner',
    'agent_runner',
    'process_agent_message',
    'initialize_agent_runner',
    'shutdown_agent_runner'
]